; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


; ; [IMPORTANT] PUT FOLLOWING LINES TO `upload_extra_config.ini`
; ;  Upload options
; ;  Configuration file ignored by Git, so Commit indipendent

; [env:tabellone]
; upload_port = COM10

; [env:pulsantiera]
; upload_port = COM12


[platformio]
extra_configs = upload_extra_config.ini

[env]
extra_scripts = git_script.py
                scripts/hardware.py
platform = espressif32@4.0.0
board = esp32dev
framework = arduino
monitor_speed = 115200


[env:tabellone]
build_src_filter = +<Tabellone>
                   +<Common>
monitor_filters = esp32_exception_decoder
build_flags = -O3
lib_deps = 
    https://github.com/adafruit/RTClib.git#1.13.0
    https://github.com/adafruit/Adafruit-MCP23017-Arduino-Library.git#1.3.0
    https://github.com/cotestatnt/esp-fs-webserver.git#1.2.5
    ; https://github.com/lorol/LITTLEFS.git
    https://github.com/bblanchon/ArduinoJson.git#v6.21.5
lib_ldf_mode = chain+
board_build.partitions = src/Tabellone/partition_table.csv
board_build.filesystem = littlefs

[env:pulsantiera]
build_src_filter = +<Pulsantiera>
                   +<Common>
monitor_filters = esp32_exception_decoder
lib_deps = 
    https://github.com/adafruit/Adafruit-MCP23017-Arduino-Library.git#1.3.0
lib_ldf_mode = chain+

[env:tabellone_OTA]
extends = env:tabellone
upload_protocol = espota
upload_port = 192.168.4.1

[env:pulsantiera_OTA]
extends = env:pulsantiera
upload_protocol = espota
upload_port = 192.168.4.10